name: casq1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_material_color_picker: ^1.2.0
  fl_chart: ^0.68.0

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.1
  google_sign_in: ^6.1.0

  # Notifications & Timezone
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # Utils
  intl: ^0.19.0
  csv: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.13.4
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  provider: ^6.1.2

  # Media & Sharing
  image_picker: ^1.1.2
  share_plus: ^10.1.0
  flutter_launcher_icons: ^0.14.4
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/cashq.png"