// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTqerQEQ8h1nC4pG0yjzro-lB5bZwLMw',
    appId: '1:804530870335:web:dc9ad9a757106abfd1408a',
    messagingSenderId: '804530870335',
    projectId: 'cashq-3e8c4',
    authDomain: 'cashq-3e8c4.firebaseapp.com',
    storageBucket: 'cashq-3e8c4.firebasestorage.app',
    measurementId: 'G-5FQZCYC6YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNc8EJhPt3MfEXYh7x593Dz5_z5mrj54',
    appId: '1:804530870335:android:6cbad059b7ec34d6d1408a',
    messagingSenderId: '804530870335',
    projectId: 'cashq-3e8c4',
    storageBucket: 'cashq-3e8c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA8RU-n9Jn_Cdn4e4YrFSR9SjO6EvUvm0',
    appId: '1:804530870335:ios:c66aa335fd342439d1408a',
    messagingSenderId: '804530870335',
    projectId: 'cashq-3e8c4',
    storageBucket: 'cashq-3e8c4.firebasestorage.app',
    iosBundleId: 'com.example.casq1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA8RU-n9Jn_Cdn4e4YrFSR9SjO6EvUvm0',
    appId: '1:804530870335:ios:c66aa335fd342439d1408a',
    messagingSenderId: '804530870335',
    projectId: 'cashq-3e8c4',
    storageBucket: 'cashq-3e8c4.firebasestorage.app',
    iosBundleId: 'com.example.casq1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKTqerQEQ8h1nC4pG0yjzro-lB5bZwLMw',
    appId: '1:804530870335:web:76917e7cc8ff34c9d1408a',
    messagingSenderId: '804530870335',
    projectId: 'cashq-3e8c4',
    authDomain: 'cashq-3e8c4.firebaseapp.com',
    storageBucket: 'cashq-3e8c4.firebasestorage.app',
    measurementId: 'G-RDH69R50J2',
  );
}
